function [t] = naiveBayesClassify(xTest, M, V, p)
    M = transpose(M);
    V = transpose(sqrt(V));
    len = length(p);
    t = arrayfun( ...
          @(x) ...
            maxId( ...
              arrayfun( ...
                @(y) prod(normpdf(xTest(x,:),M(y,:),V(y,:)))*p(y), ...
                1:len)), ...
          1:length(xTest));
    t = transpose(t);
end


function [v] = maxId(arr)
    [~,v] = max(arr);
end
